image: node:latest

variables:
 giturl: "https://$usergit$:$passgit$@@gitlab.com/vbibiv/SellerUp-Front.git"
 
stages:
 - build
 - test

cache:
 paths:
  - node_modules/

install_dependencies:
 stage: build
 script:
  - npm cache verify
  - rm package-lock.json
  - rm fr node-modules
  - npm install
  - npm install node -sass
  - npm run build-prod
 artifacts:
   paths:
     - node_modules/**
    
test_avec_ors:
 stage: test
 script: 
  - npm run test