image: node:latest
#variables:
# giturl: "https://$usergit$:$passgit$@@gitlab.com/vbibiv/SellerUp-Front.git"

stages:
 - build
 - test
 - deploy

cache:
 paths:
  - node_modules/

before_script:
  - apt-update
  - apt-get install -y node.js
  - npm cache verify
  - rm package-lock.json
  - rm -fr node_modules
  - npm install
  - npm install node-sass

install_dependencies:
 stage: build
 script:
  - npm run build-prod
 artifacts:
   paths:
     - node_modules/**
    
uni_test:
 stage: test
 script: 
  - npm i && npm test

deploy-production:
  stage: deploy
  when: manual
  script:
    - npm run deploy