image: node:latest
#variables:
# giturl: "https://$usergit$:$passgit$@@gitlab.com/vbibiv/SellerUp-Front.git"

stages:
 - build
 - test
 - deploy
 
cache:
 paths:
  - node_modules/

install_dependencies:
 stage: build
 script:
  - npm cache verify
  - rm package-lock.json
  - rm -fr node_modules
  - npm install
  - npm install node-sass
  - npm run build-prod
 artifacts:
   paths:
     - node_modules/**
    
uni_test:
 image: juristr/angular-ci-build:1.0.0
 stage: test
 script: 
  - npm run test:ci

deploy-production:
  stage: deploy
  dependencies:
    - app-build
  script:
    - npm run deploy
